import { TestQuestion } from '@/types/test';

export const TEST_QUESTIONS: TestQuestion[] = [
  {
    id: 'q1',
    title: '您的身份是？',
    options: [
      { label: '博士/博士生', value: 'phd', tags: [] },
      { label: '高管/中层管理者', value: 'executive', tags: [] },
      { label: '医生', value: 'doctor', tags: [] },
      { label: '律师', value: 'lawyer', tags: [] },
      { label: '咨询顾问', value: 'consultant', tags: [] },
      { label: '金融从业者', value: 'finance', tags: [] },
      { label: '创业者', value: 'entrepreneur', tags: [] },
      { label: '高学历职场人', value: 'professional', tags: [] },
      { label: '其他', value: 'other', tags: [] },
    ],
  },
  {
    id: 'q2',
    title: '您现在最主要的问题是？',
    options: [
      { label: '工作压力大，但不知道该不该换', value: 'pressure_stay', tags: ['high_pressure'] },
      { label: '想做副业/自由职业，但不知道从哪开始', value: 'side_start', tags: ['monetize', 'execution_block'] },
      { label: '有能力但感觉没被看见、没被认可', value: 'invisible', tags: ['externalize'] },
      { label: '想转型，但怕失败、怕损失', value: 'transition_fear', tags: ['transition_risk'] },
      { label: '在组织里受限，没有话语权', value: 'org_stuck', tags: ['org_constrained'] },
      { label: '方向太多，反而不知道选哪个', value: 'too_many', tags: ['high_pressure', 'execution_block'] },
      { label: '收入还行但没有成就感', value: 'no_fulfillment', tags: ['externalize', 'transition_risk'] },
      { label: 'AI 焦虑，担心被替代', value: 'ai_anxiety', tags: ['high_pressure', 'transition_risk'] },
    ],
  },
  {
    id: 'q3',
    title: '这个问题最近主要被什么触发？',
    options: [
      { label: '看到同行/朋友发展得更好', value: 'comparison', tags: ['high_pressure'] },
      { label: '工作中的一次冲突或挫败', value: 'conflict', tags: ['org_constrained', 'high_pressure'] },
      { label: '收入没有增长或下降了', value: 'income_drop', tags: ['monetize'] },
      { label: '身体或情绪发出了警报', value: 'burnout', tags: ['high_pressure'] },
      { label: '一次外部机会（课程/朋友邀请/创业想法）', value: 'opportunity', tags: ['transition_risk', 'monetize'] },
      { label: '长期积累的不满终于到了临界点', value: 'accumulation', tags: ['org_constrained', 'high_pressure'] },
      { label: '行业/公司变动（裁员、重组、政策）', value: 'industry_change', tags: ['org_constrained', 'transition_risk'] },
    ],
  },
  {
    id: 'q4',
    title: '如果 3 个月后没有变化，您最担心什么？',
    options: [
      { label: '情绪和身体会撑不住', value: 'health_risk', tags: ['high_pressure'] },
      { label: '错过转型的最佳时机', value: 'miss_timing', tags: ['transition_risk'] },
      { label: '继续被组织消耗，没有积累', value: 'org_drain', tags: ['org_constrained'] },
      { label: '收入越来越被动，没有第二曲线', value: 'income_passive', tags: ['monetize'] },
      { label: '能力会贬值，竞争力下降', value: 'skill_decay', tags: ['externalize', 'high_pressure'] },
      { label: '还是原地踏步，自我怀疑加重', value: 'self_doubt', tags: ['execution_block', 'high_pressure'] },
      { label: '家庭/关系因为工作状态受影响', value: 'family_impact', tags: ['high_pressure'] },
    ],
  },
  {
    id: 'q5',
    title: '您现在最像哪种状态？',
    options: [
      { label: '想得很多，但迟迟没行动', value: 'overthink', tags: ['high_pressure', 'execution_block'] },
      { label: '一直在学习/准备，但没有产出', value: 'preparing', tags: ['externalize', 'execution_block'] },
      { label: '知道方向，但被现实绑住了', value: 'bound', tags: ['org_constrained'] },
      { label: '行动了但没效果，不知道哪里错了', value: 'ineffective', tags: ['externalize', 'monetize'] },
      { label: '什么都想做，结果什么都没做好', value: 'scattered', tags: ['high_pressure', 'execution_block'] },
      { label: '在等一个合适的时机', value: 'waiting', tags: ['transition_risk', 'execution_block'] },
      { label: '已经很累了，只想要一个确定答案', value: 'exhausted', tags: ['high_pressure'] },
    ],
  },
  {
    id: 'q6',
    title: '您现在最不能承受的风险是？',
    options: [
      { label: '收入中断或大幅下降', value: 'income_loss', tags: ['transition_risk'] },
      { label: '社会身份/职业标签丢失', value: 'identity_loss', tags: ['transition_risk', 'org_constrained'] },
      { label: '时间精力投入后没有回报', value: 'wasted_effort', tags: ['execution_block', 'high_pressure'] },
      { label: '被周围人否定或不理解', value: 'social_pressure', tags: ['transition_risk'] },
      { label: '影响家庭稳定', value: 'family_stability', tags: ['transition_risk'] },
      { label: '失去组织内的资源和位置', value: 'org_position', tags: ['org_constrained'] },
      { label: '心理上再一次挫败', value: 'psychological', tags: ['high_pressure'] },
    ],
  },
  {
    id: 'q7',
    title: '您现在每周最多能拿出多少时间做改变？',
    options: [
      { label: '几乎没有，已经满负荷', value: 'none', tags: [] },
      { label: '1-2 小时', value: '1_2h', tags: [] },
      { label: '3-5 小时', value: '3_5h', tags: [] },
      { label: '5-10 小时', value: '5_10h', tags: [] },
      { label: '10 小时以上', value: '10h_plus', tags: [] },
    ],
  },
  {
    id: 'q8',
    title: '您觉得自己目前最有价值的资源是什么？',
    options: [
      { label: '专业知识/技能', value: 'expertise', tags: ['externalize'] },
      { label: '行业人脉/关系网', value: 'network', tags: ['externalize', 'monetize'] },
      { label: '组织内的职位/平台', value: 'platform', tags: ['org_constrained'] },
      { label: '学历/资质证书', value: 'credentials', tags: ['externalize'] },
      { label: '管理/带团队经验', value: 'management', tags: ['externalize'] },
      { label: '解决问题的思维方式', value: 'thinking', tags: ['externalize', 'monetize'] },
      { label: '写作/表达/教学能力', value: 'communication', tags: ['externalize', 'monetize'] },
      { label: '说不清楚', value: 'unclear', tags: ['execution_block'] },
    ],
  },
  {
    id: 'q9',
    title: '您更希望先得到什么？',
    options: [
      { label: '一个清晰的方向', value: 'clarity', tags: ['high_pressure', 'execution_block'] },
      { label: '一个可执行的第一步', value: 'first_step', tags: ['execution_block'] },
      { label: '一份理性的风险评估', value: 'risk_assessment', tags: ['transition_risk'] },
      { label: '一种把能力变现的路径', value: 'monetize_path', tags: ['monetize'] },
      { label: '一种在组织内的生存策略', value: 'org_strategy', tags: ['org_constrained'] },
      { label: '一种减少焦虑的方法', value: 'anxiety_reduce', tags: ['high_pressure'] },
      { label: '一种验证新方向的方式', value: 'validate', tags: ['transition_risk', 'monetize'] },
    ],
  },
  {
    id: 'q10',
    title: '您更接受哪种行动方式？',
    options: [
      { label: '先做一个小实验，看看反馈再决定', value: 'experiment', tags: ['transition_risk'] },
      { label: '先整理自己的能力清单，再对外展示', value: 'inventory', tags: ['externalize'] },
      { label: '先找到 1-2 个对标人物，学习路径', value: 'benchmark', tags: ['transition_risk', 'externalize'] },
      { label: '先和专业人士聊一聊，获取外部视角', value: 'consult', tags: ['high_pressure'] },
      { label: '先处理组织内的关系和位置问题', value: 'org_fix', tags: ['org_constrained'] },
      { label: '先把一个想法写出来/说出来', value: 'express', tags: ['externalize', 'execution_block'] },
      { label: '先休息，恢复精力后再行动', value: 'rest', tags: ['high_pressure'] },
    ],
  },
];
